[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_FIREBASE_API_KEY = "AIzaSyBMvLtHjKUT29g3C5XRE9LM7oMYcr86CsY"
  VITE_FIREBASE_AUTH_DOMAIN = "deuil-12369.firebaseapp.com"
  VITE_FIREBASE_DATABASE_URL = "https://deuil-12369-default-rtdb.europe-west1.firebasedatabase.app"
  VITE_FIREBASE_PROJECT_ID = "deuil-12369"
  VITE_FIREBASE_STORAGE_BUCKET = "deuil-12369.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "1007706187993"
  VITE_FIREBASE_APP_ID = "1:1007706187993:web:24a6fff9b0b6cbe5f136c8"
  VITE_FIREBASE_MEASUREMENT_ID = "G-L15WM3BN4N"
